"""CrewAI integration for Scavio Search API."""

from __future__ import annotations

from crewai_scavio.amazon import (
    ScavioAmazonOffersTool,
    ScavioAmazonProductTool,
    ScavioAmazonSearchTool,
)
from crewai_scavio.google import ScavioSearchTool
from crewai_scavio.instagram import (
    ScavioInstagramCommentRepliesTool,
    ScavioInstagramPostCommentsTool,
    ScavioInstagramPostTool,
    ScavioInstagramProfileTool,
    ScavioInstagramSearchHashtagsTool,
    ScavioInstagramSearchUsersTool,
    ScavioInstagramStoriesTool,
    ScavioInstagramTaggedPostsTool,
    ScavioInstagramUserFollowersTool,
    ScavioInstagramUserFollowingsTool,
    ScavioInstagramUserPostsTool,
    ScavioInstagramUserReelsTool,
)
from crewai_scavio.linkedin import (
    ScavioLinkedInCompanyPostsTool,
    ScavioLinkedInCompanyTool,
    ScavioLinkedInJobTool,
    ScavioLinkedInPersonAboutTool,
    ScavioLinkedInPersonPostsTool,
    ScavioLinkedInPersonTool,
    ScavioLinkedInPostCommentsTool,
    ScavioLinkedInPostTool,
    ScavioLinkedInSearchJobsTool,
)
from crewai_scavio.reddit import ScavioRedditPostTool, ScavioRedditSearchTool
from crewai_scavio.tiktok import (
    ScavioTikTokCommentRepliesTool,
    ScavioTikTokHashtagTool,
    ScavioTikTokHashtagVideosTool,
    ScavioTikTokProfileTool,
    ScavioTikTokSearchUsersTool,
    ScavioTikTokSearchVideosTool,
    ScavioTikTokUserFollowersTool,
    ScavioTikTokUserFollowingsTool,
    ScavioTikTokUserPostsTool,
    ScavioTikTokVideoCommentsTool,
    ScavioTikTokVideoTool,
)
from crewai_scavio.tiktok_shop import (
    ScavioTikTokShopCategoriesTool,
    ScavioTikTokShopCategoryProductsTool,
    ScavioTikTokShopProductReviewsTool,
    ScavioTikTokShopProductTool,
    ScavioTikTokShopResolveTool,
    ScavioTikTokShopSearchSuggestionsTool,
    ScavioTikTokShopSearchTool,
    ScavioTikTokShopShopProductsTool,
)
from crewai_scavio.walmart import ScavioWalmartProductTool, ScavioWalmartSearchTool
from crewai_scavio.youtube import (
    ScavioYouTubeChannelTool,
    ScavioYouTubeChannelVideosTool,
    ScavioYouTubeCommentsTool,
    ScavioYouTubeSearchTool,
    ScavioYouTubeStreamsTool,
    ScavioYouTubeTranscriptTool,
    ScavioYouTubeVideoTool,
)
from crewai_scavio.x import (
    ScavioXSearchTool,
    ScavioXTrendingTool,
    ScavioXTweetCommentsTool,
    ScavioXTweetRetweetersTool,
    ScavioXTweetTool,
    ScavioXUserFollowersTool,
    ScavioXUserFollowingsTool,
    ScavioXUserMediaTool,
    ScavioXUserRepliesTool,
    ScavioXUserTool,
    ScavioXUserTweetsTool,
)

__version__ = "0.5.0"

__all__ = [
    "ScavioSearchTool",
    "ScavioAmazonSearchTool",
    "ScavioAmazonProductTool",
    "ScavioAmazonOffersTool",
    "ScavioYouTubeSearchTool",
    "ScavioYouTubeVideoTool",
    "ScavioYouTubeCommentsTool",
    "ScavioYouTubeTranscriptTool",
    "ScavioYouTubeChannelTool",
    "ScavioYouTubeChannelVideosTool",
    "ScavioYouTubeStreamsTool",
    "ScavioWalmartSearchTool",
    "ScavioWalmartProductTool",
    "ScavioRedditSearchTool",
    "ScavioRedditPostTool",
    "ScavioTikTokProfileTool",
    "ScavioTikTokUserPostsTool",
    "ScavioTikTokVideoTool",
    "ScavioTikTokVideoCommentsTool",
    "ScavioTikTokCommentRepliesTool",
    "ScavioTikTokSearchVideosTool",
    "ScavioTikTokSearchUsersTool",
    "ScavioTikTokHashtagTool",
    "ScavioTikTokHashtagVideosTool",
    "ScavioTikTokUserFollowersTool",
    "ScavioTikTokUserFollowingsTool",
    "ScavioTikTokShopSearchTool",
    "ScavioTikTokShopSearchSuggestionsTool",
    "ScavioTikTokShopProductTool",
    "ScavioTikTokShopProductReviewsTool",
    "ScavioTikTokShopCategoriesTool",
    "ScavioTikTokShopCategoryProductsTool",
    "ScavioTikTokShopShopProductsTool",
    "ScavioTikTokShopResolveTool",
    "ScavioInstagramProfileTool",
    "ScavioInstagramUserPostsTool",
    "ScavioInstagramUserReelsTool",
    "ScavioInstagramTaggedPostsTool",
    "ScavioInstagramStoriesTool",
    "ScavioInstagramPostTool",
    "ScavioInstagramPostCommentsTool",
    "ScavioInstagramCommentRepliesTool",
    "ScavioInstagramSearchUsersTool",
    "ScavioInstagramSearchHashtagsTool",
    "ScavioInstagramUserFollowersTool",
    "ScavioInstagramUserFollowingsTool",
    "ScavioLinkedInCompanyPostsTool",
    "ScavioLinkedInCompanyTool",
    "ScavioLinkedInJobTool",
    "ScavioLinkedInPersonAboutTool",
    "ScavioLinkedInPersonPostsTool",
    "ScavioLinkedInPersonTool",
    "ScavioLinkedInPostCommentsTool",
    "ScavioLinkedInPostTool",
    "ScavioLinkedInSearchJobsTool",
    "ScavioXSearchTool",
    "ScavioXTrendingTool",
    "ScavioXTweetCommentsTool",
    "ScavioXTweetRetweetersTool",
    "ScavioXTweetTool",
    "ScavioXUserFollowersTool",
    "ScavioXUserFollowingsTool",
    "ScavioXUserMediaTool",
    "ScavioXUserRepliesTool",
    "ScavioXUserTool",
    "ScavioXUserTweetsTool",
]
